### ISSUE TITLE
Se puede poner en producción este proyecto?

### ISSUE THREAD

**Issue by Isidro-hernndez** [CarlosArturoFyuler/recoleccion#1]
Buenas tardes, eh intentado levantar el proyecto, pero me pide los accesos de telcel, mi pregunta es si aún se puede utilizar este proyecto o ya esta inactivo?

**Comment by CarlosArturoMe** [comment]
Hola! Ya no soy el encargado de este repositorio, pero puedes mandar un correo a gobiernoelectronico@xalapa.gob.mx para que te den más informes; también me parece que en esta liga puedes hacer peticiones https://ayuntamiento.xalapa.gob.mx/web/gobierno-abierto
espero te sirva.

**Comment by Isidro-hernndez** [comment]
Muchas gracias por tu atención.
